{
 "title": "DZ3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "1. Latency 0.5, 0.95, 0.99, max (per endpoint)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))))",
     "legendFormat": "0.5: {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))))",
     "legendFormat": "0.95: {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))))",
     "legendFormat": "0.99: {{uri}}"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, uri)(rate(http_server_requests_seconds_bucket[1m]))))",
     "legendFormat": "max: {{uri}}"
    }
   ]
  },
  {
   "title": "2. RPS (per endpoint)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "3. Error Rate (per endpoint)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "4. Latency 0.5, 0.95, 0.99, max (via ingress)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))))\n",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))))\n",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))))\n",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m]))))\n",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "5. RPS (via ingress)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "6. Error Rate (via ingress)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[5m]))"
    }
   ]
  },
  {
   "title": "7. Memory consumtion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes)"
    }
   ]
  },
  {
   "title": "8. CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_cpu_usage_seconds_total)"
    }
   ]
  }
 ]
}