apiVersion: v1
kind: ConfigMap
metadata:
  name: dz2-config
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://my-release-mariadb:3306/my_db
  SPRING_DATASOURCE_USERNAME: root
---
apiVersion: v1
kind: Secret
metadata:
  name: dz2-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: c2VjcmV0cGFzc3dvcmQxMjM=