apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-db-init
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: mariadb:latest
          env:
            - name: MARIA_HOST
              value: {{(include "mariadb.fullname" .)}}
          command:
            - sh
            - "-c"
            - |
              until mysqladmin ping -u root -h $MARIA_HOST  -p'{{.Values.mariadb.auth.rootPassword }}';
              do echo waiting for database; sleep 2; done;
      containers:
        - name: myapp-db-init
          image: mariadb
          command:
            - sh
            - "-c"
            - |
              mysql -u root -h {{(include "mariadb.fullname" .)}} -p'{{.Values.mariadb.auth.rootPassword }}' <<'EOF'
                CREATE DATABASE IF NOT EXISTS my_db;
                USE my_db;
                CREATE SEQUENCE IF NOT EXISTS hibernate_sequence;
                CREATE TABLE IF NOT EXISTS `user_entity` (
                    `id` bigint(20) NOT NULL,
                    `email` varchar(255) DEFAULT NULL,
                    `first_name` varchar(255) DEFAULT NULL,
                    `last_name` varchar(255) DEFAULT NULL,
                    `phone` varchar(255) DEFAULT NULL,
                    `username` varchar(255) DEFAULT NULL,
                    PRIMARY KEY (`id`) )
                    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
                  REPLACE INTO user_entity (id, email, first_name, last_name, phone, username)
                    VALUES ('74', 'email74', 'firstName74', 'lastName74', 'phone74', 'username74');
                  SELECT * FROM user_entity;
              EOF
      restartPolicy: Never
  backoffLimit: 4